name = "deter-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

[vars]
TARGET_ZONE_ID = "YOUR_TARGET_ZONE_ID"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "YOUR_KV_NAMESPACE_ID"
